[{
	"resource": "/workspaces/rutinaappnew/src/components/rutinas/DiaRutinaItem.tsx",
	"owner": "typescript",
	"code": "2305",
	"severity": 8,
	"message": "El módulo '\"@/types/rutinas\"' no tiene ningún miembro 'Dia' exportado.",
	"source": "ts",
	"startLineNumber": 4,
	"startColumn": 3,
	"endLineNumber": 4,
	"endColumn": 6,
	"modelVersionId": 1,
	"origin": "extHost2"
},{
	"resource": "/workspaces/rutinaappnew/src/components/rutinas/DiaRutinaItem.tsx",
	"owner": "typescript",
	"code": "2305",
	"severity": 8,
	"message": "El módulo '\"@/types/rutinas\"' no tiene ningún miembro 'Ejercicio' exportado.",
	"source": "ts",
	"startLineNumber": 5,
	"startColumn": 3,
	"endLineNumber": 5,
	"endColumn": 12,
	"modelVersionId": 1,
	"origin": "extHost2"
},{
	"resource": "/workspaces/rutinaappnew/src/components/rutinas/DiaRutinaItem.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "El parámetro 'ejercicio' tiene un tipo 'any' implícitamente.",
	"source": "ts",
	"startLineNumber": 71,
	"startColumn": 30,
	"endLineNumber": 71,
	"endColumn": 39,
	"modelVersionId": 1,
	"origin": "extHost2"
},{
	"resource": "/workspaces/rutinaappnew/src/components/rutinas/DiaRutinaItem.tsx",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "El tipo '{ key: any; ejercicio: any; diaId: any; actualizarEjercicio: (idDia: number, idEjercicio: number, campo: string | number | symbol, valor: string | boolean) => void; eliminarEjercicio: (idDia: number, idEjercicio: number) => void; }' no se puede asignar al tipo 'IntrinsicAttributes & Props'.\n  La propiedad \"ejercicio\" no existe en el tipo \"IntrinsicAttributes & Props\". ¿Quería decir \"ejercicioId\"?",
	"source": "ts",
	"startLineNumber": 76,
	"startColumn": 13,
	"endLineNumber": 76,
	"endColumn": 22,
	"modelVersionId": 1,
	"origin": "extHost2"
}]